### PR TITLE
Website

### PR DESCRIPTION
**Pull request by LeoKids**
You can Choose what is Okay for you,HTML4,XTHML Supports Older Browsers While HTML5 and XHTML5 Supports Browsers That Can support Basic/Complete HTML5 Code.

You can Modify the Code to Not put the Local Thing,so Dont worry if that doesnt Work.

Also that is Leogames2016´s Website and Not my Website.

Can you Add this?

### CODE REVIEW

**Comment by PF94** [comment]
can you put this on a new folder? Theres a error within some subsisted which causes 404s because the main page's location broke after the reorginazation.

**Comment by LeoKids** [comment]
I Can but please

**Comment by LeoKids** [comment]
Do a Folder for me

**Comment by PF94** [comment]
FINE.

**Pull request merged**
